version: '3'

services:
  server:
    container_name: servidor-rateLmiter
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/.env
    networks:
      - rateLimiter
  redis:
    container_name: redis-rateLimite
    image: redis
    ports:
      - "6379:6379"
    networks:
      - rateLimiter

networks:
  rateLimiter:
    name: rateLimiter
    driver: bridge